SELECT
    TO_CHAR(f.SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE,
    f.PRODUCT_ID,
    NULL AS USER_ID,
    f.SALES_AMOUNT
FROM
    OFFLINE_SALE f
WHERE
    TO_CHAR(f.SALES_DATE, 'YYYY-MM') = '2022-03'
UNION ALL
SELECT
    TO_CHAR(o.SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE,
    o.PRODUCT_ID,
    o.USER_ID,
    o.SALES_AMOUNT
FROM
    ONLINE_SALE o
WHERE
    TO_CHAR(o.SALES_DATE, 'YYYY-MM') = '2022-03'
ORDER BY
    SALES_DATE ASC,
    PRODUCT_ID ASC,
    USER_ID ASC;
