SELECT
    a.CAR_ID,
    a.CAR_TYPE,
    (a.DAILY_FEE* 30* (1-b.DISCOUNT_RATE*0.01) ) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR a , CAR_RENTAL_COMPANY_DISCOUNT_PLAN  b
WHERE
    a.CAR_TYPE IN ('세단','SUV') 
    AND B.DURATION_TYPE = '30일 이상'
    AND a.CAR_TYPE = b.CAR_TYPE
    AND (a.DAILY_FEE* 30* (1-b.DISCOUNT_RATE*0.01) ) BETWEEN 500000 AND 2000000
    AND CAR_ID  NOT IN
      (SELECT CAR_ID        
         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY  
        WHERE END_DATE >= TO_DATE('2022-11-01','YYYY-MM-DD')
      )
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC