SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (SELECT MAX(SIZE_OF_COLONY)
     FROM ECOLI_DATA AS sub
     WHERE YEAR(sub.DIFFERENTIATION_DATE) = YEAR(main.DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM 
    ECOLI_DATA AS main
ORDER BY YEAR, YEAR_DEV
