WITH HourSlot AS (
    SELECT LEVEL - 1 AS HOUR
    FROM dual
    CONNECT BY LEVEL <= 24
)
SELECT
    hs.HOUR,
    COALESCE(COUNT(TO_CHAR(a.DATETIME, 'HH24')), 0) AS COUNT
FROM
    HourSlot hs
LEFT JOIN
    ANIMAL_OUTS a ON TO_CHAR(a.DATETIME, 'HH24') = hs.HOUR
GROUP BY
    hs.HOUR
ORDER BY
    hs.HOUR;
