SELECT
    EXTRACT(YEAR FROM SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(DISTINCT USER_ID)
                                     FROM USER_INFO
                                     WHERE EXTRACT(YEAR FROM JOINED) = 2021), 1) AS PURCHASED_RATIO
FROM 
    USER_INFO 
    INNER JOIN ONLINE_SALE USING (USER_ID)
WHERE 
    EXTRACT(YEAR FROM JOINED) = 2021
GROUP BY 
    EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
ORDER BY 
    EXTRACT(YEAR FROM SALES_DATE) ASC, 
    EXTRACT(MONTH FROM SALES_DATE) ASC;