SELECT 
    A.ID, 
    CASE 
        WHEN A.QUARTILE = 1 THEN 'CRITICAL'
        WHEN A.QUARTILE = 2 THEN 'HIGH'
        WHEN A.QUARTILE = 3 THEN 'MEDIUM'
        ELSE 'LOW' 
    END AS COLONY_NAME
FROM (
    SELECT 
        ID, 
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS QUARTILE
    FROM 
        ECOLI_DATA
) A
ORDER BY 
    A.ID