WITH firstGen AS (
    SELECT ID, PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
secondGen AS (
    SELECT ID, PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (SELECT ID FROM firstGen)
)
SELECT ID
FROM ECOLI_DATA
WHERE PARENT_ID IN (SELECT ID FROM secondGen)